### ISSUE TITLE
InputCheckboxMultiple changed wrapping from `<label>` to `<div>`

### ISSUE THREAD

**Issue by donatasben** [juergenweb/FrontendForms#15]
Hi @juergenweb 
I have tried to update the module (2.2.13) but I noticed it started wrapping multiple checkboxes with a `<div>` instead of `<label>` as in previous versions. I haven't changed any of my setup, tested back with older version (2.2.3) and can confirm that it changed.

Maybe you implemented some option to choose which tag is used in multiple checkboxes and radios?
The `appendLabelOnCheckboxes` doesn't seem to have effect on this.

2.2.3 Old (Good):
<img width="297" alt="SCR-20240821-nais" src="https://github.com/user-attachments/assets/ae21c508-6fc2-4feb-afa9-c7cee04ccae8">

2.2.13 New (Bad):
<img width="302" alt="SCR-20240821-naop" src="https://github.com/user-attachments/assets/d2feb9a4-65b5-429f-9241-d94d8cd57b0f">

**Comment by juergenweb** [comment]
Hello @donatasben 

I was on vacation, but I will check this as soon as possible. I can remember there was a problem with <br> tags in the past in the vertical alignment of multiple checkboxes. I guess this problem results from this change. 

Best regards Jürgen

**Comment by juergenweb** [comment]
I have set the tag to "label" and I haved changed 2 other files too. I guess there was a copy and paste problem in the past, which was responsible for the div tag instead of the label tag. 
I have tested it with all frameworks and with no framework on radio multiple and checkbox multiple:

![Multiples](https://github.com/user-attachments/assets/7ed2747c-7a50-4e76-bdf4-500ccff69333)

I have added it to Github now, but I will bump up the version after I have finished the new Slider Captcha (it is ready now, but there are small CSS bugs that I have to correct, before upgrading to the next version.

If you do not want to wait until the next update please replace the following files with the one from Github:

- Formelements/Textelements/Label.php
- Formelements/Inputelements/Inputs/InputRadioMultiple.php
- Formelements/Inputelements/Inputs/InputCheckboxMultiple.php

I will closes this issue for now. If this update does not solve your problem or you discover a new problem, please open a new issue report.

**Comment by donatasben** [comment]
Thank you @juergenweb! It works as expected with the newest version 2.2.14 🙏

**Comment by juergenweb** [comment]
Glad to hear that!!
