### ISSUE TITLE
`wireClassNamespace()` in `formContainsElementByClass()` grabs wrong class names in some server setups

### ISSUE THREAD

**Issue by donatasben** [juergenweb/FrontendForms#19]
Hi,
I have ran into a weird issue again: my forms stopped rendering at all today and after an emotional and extensive debugging session I found out that `wireClassNamespace()` when used in some functions in `FrontendForms/Formelements/Form.php` returns a wrong class prefix for 'Button' class, while searching in form's `render()` method.

It might be a very rare case, but probably just recently my hosting provider might have installed "[Phalcon](https://phalcon.io/)" php extension/framework and so the wireClassNamespace() returns `\Phalcon\Html\Helper\Button` instead of expected `\FrontendForms\Button`, and makes the whole form not be rendered - no "$buttons" found in `render()` method...

Would it be possible for you to change where the classes should be searched for, to make sure it looks for FrontendForms classes, not any that might exist?

My dirty temporary fix is to append the '\FrontendForms' class namespace manually:
```
public function formContainsElementByClass(string $className): int
        {
            // $className = wireClassNamespace($className, true);
            $className = '\\FrontendForms\\'.$className;
            ...
```

**Comment by juergenweb** [comment]
Hello @donatasben 

This is a strange issue!! I do not know how to solve this issue, so I have used your fix and replaced the wireClassNamespace function by using a hard-coded namespace instead. This should not have side-effects. I have replaced it 2 times inside the Form.php.
So please replace your Form.php with the current one on Github and confirm that everything works fine. If so, then the fix is in the next update.
Thanks for reporting this issue and providing a fix to it.

**Comment by donatasben** [comment]
Thanks, @juergenweb, this fix works for me 👍 
It definitely is a strange issue out of the blue for seemingly no reason... Hope this helps anyone else.
