### ISSUE TITLE
SelectMultiple

### ISSUE THREAD

**Issue by pmichaelis** [juergenweb/FrontendForms#3]
Sorry, for bothering you all the time, but I am testing your module on a project.

Your Documentation says:

`$select = new InputSelectMultiple('mySelect');`

I think it must be "SelectMultiple"

If multiple values are selected:

`$form->getValue('mySelect');`

returns a Sting:
string(7) "array-5"

Thanks for help

**Comment by juergenweb** [comment]
Hello Phillip

First of all, I am happy that you are testing the module intensively - so please open an issue whenever you discover an error, an idea what new features could be integrated or something else ;-).

You are right: Multiselect should return an array an not a string. The cause was the sanitizer text which will be added to all input elements by default and this sanitizer converts the array into a string on multivalue inputfields.
I have removed the adding of the text sanitizer on all multivalue inputfields and now they return an array. Please test it and let me know.

Second issue: You are right - there was a mistake in the docs. SelectMultiple is correct and InputSelectMultiple is wrong. I have corrected it (good eagle eyes ;-)

Best regards

**Comment by pmichaelis** [comment]
Hey Juergen,

thanks for all your effort and your help.
In my case the submittetd value of the multi select is still converted to string.
Did you push into the master branch?

Thanks
Philipp

**Comment by juergenweb** [comment]
You are right
There is something strange going on. I found some other mistakes to. I guess that PHP Storm has changed some things by pressing a wrong button on optimizing the code. I am very busy at the moment, but I will take a more careful look within the next days. Please be patient. I will inform you.

Best regards Jürgen

**Comment by juergenweb** [comment]
Hello Phillip

I have fixed the issue and bumped up the version to 2.0.6. I have moved all the validation methods from the Form class to an extra class called FormValidation.
So please download the whole module and test it intensively.
In my testing environment it works as expected.
Please let me know if it works in your test environment too.

Best regards Jürgen

**Comment by pmichaelis** [comment]
Hey Juergen,

nice, that seems to work properly. The Select is value is now an array.
Thank you so much!

Philipp

**Comment by juergenweb** [comment]
Hey Phillip, 

glad to hear that :-)
If you have ideas on features to add too, please let me know.

Jürgen
