### ISSUE TITLE
Request: Make `input_captchaFontFamily` and `input_captchaFonts` settings use relative paths

### ISSUE THREAD

**Issue by donatasben** [juergenweb/FrontendForms#8]
Hi, another small change request from me :)

I've noticed that `input_captchaFontFamily` and `input_captchaFonts` module settings are keeping full server disk paths in them. If I want to do a full database migration (or use RockMigrations export code function) - the full paths are carrying over and they become incorrect when used in another server. I then have to keep this in mind and update after each migration.

Could you please make these settings save only the relative paths, like starting from `/site/` and, maybe, append server disk path "on the fly" when they are used by the module?

That would make FrontendForms config be fully "portable" and "server-independant" :)

**Comment by juergenweb** [comment]
Hello Donatas

Thanks for reporting this issue!

You will become more and more a FrontendForms expert with an eagle-eye on improvements. ;-)

Your request has been merged  to the new version 2.1.65, which is available for download now. It should work as expected, but keep an eye if there are unwanted side-effects (I have no one discovered on my site, but who knows...).

Here is the [Changelog](https://github.com/juergenweb/FrontendForms/blob/main/CHANGELOG.md#2165-2024-02-22).

Let me know if it works for you!

Jürgen

**Comment by donatasben** [comment]
I am now an even happier FormsFrontender 😆

**Comment by juergenweb** [comment]
Hello Donatas

I have discovered that it is important that you have to do a "Refresh" of the font files first to find all font files with their relative path. I have added this step now to the changelog file. Otherwise the "old path" will not be changed.

So please read the [changelog](https://github.com/juergenweb/FrontendForms/blob/main/CHANGELOG.md#2165-2024-02-22) file once more and check your font files paths, if they are relative after you have followed the steps.

Best regards
